packer {
  required_plugins {
    azure = {
      source  = "github.com/hashicorp/azure"
      version = "~> 1"
    }
  }
}

source "azure-arm" "autogenerated_1" {
  azure_tags = {
    udacity = "azure-devops-proj-01"
  }
  client_id                         = "YOUR CLIENT ID"
  client_secret                     = "YOUR SECRET ID"
  image_offer                       = "UbuntuServer"
  image_publisher                   = "Canonical"
  image_sku                         = "18.04-LTS"
  location                          = "uksouth"
  managed_image_name                = "packer-image"
  managed_image_resource_group_name = "udacity-azure-devops-proj-01"
  os_type                           = "Linux"
  subscription_id                   = "YOUR SUBSCRIPTION ID"
  tenant_id                         = "YOUR TENANT ID"
  vm_size                           = "Standard_B1s"
}

build {
  sources = ["source.azure-arm.autogenerated_1"]

  provisioner "shell" {
    inline         = ["echo 'Hello, World!' > index.html", "nohup busybox httpd -f -p 80 &"]
    inline_shebang = "/bin/sh -x"
  }

}
